#!/bin/sh
read -d '\n' Pyld << 'String'
{
        "Rqst": "Estate/Prjct[TP]:update",
        "Prjc": "e8750a8b-d538-4ea6-b66a-d2e0d16ec7c4",
        "Seed": {
                "Value": 1048576
        }
}
String
curl --unix-socket "/tmp/DOrch" -X POST -d "$Pyld" 'http://DOrch/v5'
