#!/bin/sh
read -d '\n' Pyld << 'String'
{
        "Rqst": "Estate/Drive/Flash:fetch",
        "Drvv": "a4e0968f-7f07-4d74-a632-3dd2ab8aabbb",
        "Flsh": "ec43fa46-db95-4451-9bd0-2c2f7e9b14af"
}
String
curl --unix-socket "/tmp/DOrch" -X POST -d "$Pyld" 'http://DOrch/v5'
