#!/bin/sh
read -d '\n' Pyld << String
{
        "Rqst": "Estate/Prjct/Sftwr[Pulse]:fetch",
        "Prjc": "e8750a8b-d538-4ea6-b66a-d2e0d16ec7c4"
}
String
curl --unix-socket "/tmp/DOrch" -X POST -d "$Pyld" 'http://DOrch/v5'
