#!/bin/sh
read -d '\n' Pyld << 'String'
{
        "Rqst": "Estate/Drive[SpaceAlwnc]:update",
        "Drvv": "ffae98bd-527f-4af5-89aa-2317e30594ba",
        "Seed": {
                "NewCpcty": 17179869184
        }
}
String
curl --unix-socket "/tmp/DOrch" -X POST -d "$Pyld" 'http://DOrch/v5'
