#!/bin/sh
read -d '\n' Pyld << String
{
        "Rqst": "Estate/Prjct/Sftwr:launch",
        "Prjc": "e8750a8b-d538-4ea6-b66a-d2e0d16ec7c4",
        "Seed": {
                "OldInstncStopWindow": 0,
                "CntnrUserID": 0,
                "AutoRstrt": 1
        }
}
String
curl --unix-socket "/tmp/DOrch" -X POST -d "$Pyld" 'http://DOrch/v5'
