#!/bin/sh
read -d '\n' Pyld << String
{
        "Rqst": "Estate/Prjct/Store/Pot/Drctry:create",
        "Prjc": "e8750a8b-d538-4ea6-b66a-d2e0d16ec7c4",
        "Seed": {
                "Drctry": "/elmnt-01",
                "Mode": "rwx:rwx:rwx"
        }
}
String
curl --unix-socket "/tmp/DOrch" -X POST -d "$Pyld" 'http://DOrch/v5'
