#!/bin/sh
read -d '\n' Pyld << 'String'
{
        "Rqst": "Estate:intlz",
        "Seed": {
                "ID": "01963657-d4de-7295-8603-b4f06a94b121",
                "CorePeakPower": 4096,
                "Core": [4096, 4096, 4096, 4096],
                "DomainName": "host-g1.qbqetell.ng",
                "PublicIpAdrs": "98.85.0.199"
        }
}
String
curl --unix-socket "/tmp/DOrch" -X POST -d "$Pyld" 'http://DOrch/v5'
