#!/bin/sh
read -d '\n' Pyld << 'String'
{
        "Rqst": "Estate/Drive:intlz",
        "Seed": {
                "DrivePathID": "/dev/nvme2n1"
        }
}
String
curl --unix-socket "/tmp/DOrch" -X POST -d "$Pyld" 'http://DOrch/v5'
