#!/bin/sh
read -d '\n' Pyld << String
{
        "Rqst": "Estate/Prjct/NtwrkID/TlsKey[MountPoint]:update",
        "Prjc": "e8750a8b-d538-4ea6-b66a-d2e0d16ec7c4",
        "Seed": {
                "MountPoint": [
                        "/var/tmp/tls.01.key",
                        "/var/tmp/tls.02.key"
                ]
        }
}
String
curl --unix-socket "/tmp/DOrch" -X POST -d "$Pyld" 'http://DOrch/v5'
